---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: self-service-customers
  name: self-service-customers
  namespace: self-service
spec:
  selector:
    matchLabels:
      app: self-service-customers
  template:
    metadata:
      labels:
        app: self-service-customers
    spec:
      containers:
        - image: 594646746001.dkr.ecr.us-east-1.amazonaws.com/self-service-customers:latest
          name: self-service-customers
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
          env:
            - name: PORT
              value: "8080"
            - name: DYNAMO_TABLE_CUSTOMERS
              value: self-service-customers-prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: self-service-customers
  name: self-service-customers
  namespace: self-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: self-service-customers
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: self-service-customers
  namespace: self-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-service-customers
  minReplicas: 2
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: self-service-customers
  namespace: self-service
spec:
  gateways:
    - self-service-gateway
  hosts:
    - api.cloudburger.com.br
  http:
    - name: self-service-customers
      match:
        - uri:
            prefix: /customers
      route:
        - destination:
            host: self-service-customers